### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by leah-crunchy** [unifiedstreaming/live-demo#4]
when trying to build the ffmpeg docker image, I got the following error: 

```
#6 17.61 bzip2: Compressed file ends unexpectedly;
#6 17.61 	perhaps it is corrupted?  *Possible* reason follows.
#6 17.61 bzip2: No error information
#6 17.61 	Input file = (stdin), output file = (stdout)
```

After a decent amount of troubleshooting, I realized that the `curl` command was failing due to the SSL cert on the server being expired. I did this by removing the `-s` silent flag and getting this error: 

```
#7 18.93 curl: (60) SSL certificate problem: certificate has expired
#7 18.93 More details here: https://curl.haxx.se/docs/sslcerts.html
#7 18.93
#7 18.93 curl failed to verify the legitimacy of the server and therefore could not
#7 18.93 establish a secure connection to it. To learn more about this situation and
#7 18.93 how to fix it, please visit the web page mentioned above.
```

The workaround was to `--insecure ` to the the [curl command here](https://github.com/unifiedstreaming/live-demo/blob/master/ffmpeg/Dockerfile#L35) and I was able to build. 

I'm fairly certain that ya'll can't do anything about this. But, I wanted to place an issue to track and if anyone else runs into the problem, there is a workaround here.

**Comment by markogle** [comment]
This is because the image hasn't been updated for a while so was still using alpine:3.4, which doesn't have up to date certificates trusted. Updated it to alpine:3.15 so the SSL certificate is now properly trusted and the image builds correctly.
